task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 10
remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./datasets/ruod/RUOD_pic/train/
    ann_file: ./datasets/ruod/RUOD_ANN/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./datasets/ruod/RUOD_pic/val/
    ann_file: ./datasets/ruod/RUOD_ANN/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
